# Generated by Django 5.0 on 2025-10-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='screen_name',
            field=models.CharField(max_length=50),
        ),
    ]
